In [2]:
import numpy as np

In [3]:
x_3D= np.array([np.array([8., 1, 3]), np.array([4., 5, 6]), np.array([4., 1, 5]), np.array([2., 1, 15])])

In [4]:
x_3D

array([[ 8.,  1.,  3.],
       [ 4.,  5.,  6.],
       [ 4.,  1.,  5.],
       [ 2.,  1., 15.]])

In [6]:
x_2D = x_3D.T[:][:2].T

In [7]:
x_2D

array([[8., 1.],
       [4., 5.],
       [4., 1.],
       [2., 1.]])

In [8]:
first_point = np.linalg.norm(x_2D, axis = 1).argmin()

In [9]:
x_3D[first_point]

array([ 2.,  1., 15.])